### ISSUE TITLE
Adding Custom Models Folder  Error 

### ISSUE THREAD

**Issue by DJboutit** [upscayl/custom-models#1]
I have download the custom models folder when I select this folder to add it I get this error 

![Upscaly Error](https://github.com/upscayl/custom-models/assets/38142712/69a1cf13-2a81-4a11-abee-875fffec9de0)

**Comment by NayamAmarshe** [comment]
The folder name should be models.

**Comment by DJboutit** [comment]
The folder I am selecting is 100% called models

**Comment by NayamAmarshe** [comment]
Okay, checked the code, apparently I used the UNIX slashes which aren't supported on Windows.
I'll update the exe.

**Comment by NayamAmarshe** [comment]
It's fixed now :) Let me know if it's working for you.

Unfortunately, I cannot make any other folder name work so it has to be models. It should be fine on Windows as well now, I tested with WINE haha.

**Comment by DJboutit** [comment]
Windows 10 it works now thanks for the update
