### ISSUE TITLE
Any chance for something like add-detail-xl.safetensors

### ISSUE THREAD

**Issue by worldoptimizer** [upscayl/custom-models#15]
Would it be possible to add details when upscaling like in add-detail-xl.safetensors
Best regards

Max

**Comment by NayamAmarshe** [comment]
Could you please describe in detail what you mean?

**Comment by AFOLcast** [comment]
add-detail is a lora. It adds details to SDXL generations. I imagine our friend above is hoping that he or she might be able to do GAN-style upscaling, where details are added as the image resolution is increased.

**Comment by NickPelo** [comment]
Since I upscaled one of my own photos from my HD all of my1,000,000 photos and also on the sites that I used  to download the appear like AI to my eyes. Is it from Upskayl or is universal law for legal rights of Photographers? Because I also saw the same thing in manty PCs of other people

**Comment by NickPelo** [comment]
It Happened about 6 months ago!!! Please if so
mebody knows anything about this!!!

**Comment by NayamAmarshe** [comment]
Answered here: https://github.com/upscayl/upscayl/issues/931
