### ISSUE TITLE
Request: Models for upscaling CG/3D renderings

### ISSUE THREAD

**Issue by vfxninjaeditor** [upscayl/custom-models#2]
Would be awesome to see some models for upscaling 3D renders/CGI. Would help save tremendous amounts of time when rendering projects where you need a 4K output or higher.

**Comment by NayamAmarshe** [comment]
I'd honestly make my own models if I had some investment.

It takes a lot of money and hardware to train these models.

**Comment by CWBudde** [comment]
Is there a document that explains the process? What is necessary to train a model? Basically I guess just a (large) set of training data, computing power and the right algorithm. Maybe you can hint me for the latter (especially for a model that works with Upscayl. Given the fact that it is open source, it shouldn't be too complicated to find enought supporters.
