### ISSUE TITLE
[enhancement] Clarity / Details model

### ISSUE THREAD

**Issue by MatheoJT** [upscayl/custom-models#21]
# Enhanced Image Upscaling Model Suggestion

Hello,

I understand that this has been suggested before, but I believe the previous explanations were not clear enough. So, I'd like to provide a more detailed explanation here.

---

The idea is to incorporate a model that not only upscales images but also enhances the details, making the images more realistic. For example, consider the following AI models:

- [Clarity AI](https://github.com/philz1337x/clarity-upscaler)
- [Krea AI](https://www.krea.ai/home)
- [Magnific AI](https://magnific.ai/)

---

Clarity AI, which is open source, uses the following models that might be helpful:

- [Juggernaut](https://civitai.com/models/46422/juggernaut)
- [Add More Details](https://civitai.com/models/82098?modelVersionId=87153)
- [SDXLrender](https://civitai.com/models/171159?modelVersionId=236130)

---

If an open source AI already exists, why should you add this model to Upscaly? Here are my reasons:

1. **Ease of Use**: Your software is user-friendly and provides a one-click install solution for image upscaling.
2. **Setup Difficulty**: Setting up Clarity AI can be challenging, especially for those unfamiliar with using, for example, Stable Diffusion.
3. **Compatibility**: Your software works on almost every PC, whereas I've never been able to get Stable Diffusion to work on my PC.

---

I hope this model suggestion can be considered for future additions to the software. Thank you!

**Comment by KarelAI** [comment]
I think you are a bit confused.
If you have never been able to run Stable Diffusion, implementing this would make you unable to use it..
An upscale model is not the same as a SDXL checkpoint and a lora.... What the three projects you mentioned use is a set of all of the above, they simply added a web page or a GUI with A1111 or ComfyUI under the hood.

**Comment by MatheoJT** [comment]
okay, I thought upscale models worked a bit the same way, then Ill wait until I have an nvidia gc 😅
