### ISSUE TITLE
Add AuraSR GigaGAN model

### ISSUE THREAD

**Issue by GeorgeDeac** [upscayl/custom-models#22]
A new open source SOTA model based on GigaGAN was released, it might be a great addition to the base models:
https://github.com/fal-ai/aura-sr

**Comment by technerd-official** [comment]
Just saw this. Can we put it ourselves into Upscayl, if yes how since it's a *.safetensors file.

**Comment by NayamAmarshe** [comment]
Already answered here: https://github.com/upscayl/upscayl/issues/931
