### ISSUE TITLE
Continuation from the previous issue.....  It Happened about 6 months ago!!! Please if somebody knows anything about this!!!

### ISSUE THREAD

**Issue by NickPelo** [upscayl/custom-models#24]
It Happened about 6 months ago!!! Please if so
mebody knows anything about this!!!

_Originally posted by @NickPelo in https://github.com/upscayl/custom-models/issues/15#issuecomment-2275584805_

**Comment by NayamAmarshe** [comment]
Already answered here: https://github.com/upscayl/upscayl/issues/931
