### ISSUE TITLE
Cannot add custom models folder (Windows 10)

### ISSUE THREAD

**Issue by Wlassko** [upscayl/custom-models#4]
Hi,

i tryed to add custom models folder by [instructions here](https://github.com/upscayl/custom-models) (download zip, extract, select models folder) , but if I select folder "models" then Upscayl report error:

![ups251_err](https://github.com/upscayl/custom-models/assets/121111280/45edd59b-053c-40c6-88e6-9bfb8d7b0947)
Please make sure that folder name is 'models' and nothing else.

log: 🐞 BACKEND REPORTED:  ❌ Invalid Custom Models Folder Detected: Not a 'models' folder

I dont know what I doing wrong. Upscayl 2.5.1, OS Windows 10 x64 19045.3031, I tryed run Upscayl as admin, extract folder "models" to root C: drive (C:\models) , but nothing help, still the same error. Thanks for help.

**Comment by NayamAmarshe** [comment]
Try putting the folder somewhere else. Maybe in Documents.

**Comment by NayamAmarshe** [comment]
> Thanks for tip - results:
> 
> **C:\Users\UserName\Documents\models** - Error **C:\Users\Public\Documents\models** - Error **C:\Documents\models** - Error **C:\models** - Error ... any other drive - root or next folders - Error
> 
> And if I copy models to Upscayl folder (Program Files) models then nothing - Upscayl show only basic models, ignore custom added. I dont know what to do. But anyway thanks. Maybe others in newer Windows 11 doesnt have any problems with custom models, I dont know. Thanks for trying to help me, and sorry for wasting your time :)

Please don't apologize, if I missed an edge case, I am to be blamed.
That's very strange that it gives you the error.

Could you please try to select a model and after the error appears, copy the log (using the copy button) from the settings tab and paste it here in code blocks?
![image](https://github.com/upscayl/custom-models/assets/25067102/272a815c-52aa-464f-8b69-10b0a03fdc90)

Thank you!
