### ISSUE TITLE
Renaming a model

### ISSUE THREAD

**Issue by Kim2091** [upscayl/custom-models#7]
Can you please rename the Ultrasharp model in this repo? I'm the author of the "real" UltraSharp. I understand why this was done, but I really don't want any confusion surrounding which model is which. Thank you 🙂

**Comment by NayamAmarshe** [comment]
No problem. I'll change the name :)

**Comment by Kim2091** [comment]
@NayamAmarshe Sorry to bug you, but is there any follow up on this? It's actually confused a few people now. Thanks

**Comment by NayamAmarshe** [comment]
@Kim2091 Oh I'm very very sorry! I forgot to do it, been a bit busy. I'll rename it right away, sorry for the delay.

**Comment by NayamAmarshe** [comment]
Done :) 
I apologize again for the delay!
